Bài 1: LÀM QUEN VỚI PYTORCH


Bài 1. Tạo Tensor cơ bản

In [2]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


Bài 2. Tạo các Tensor thường dùng

In [3]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.3080, 0.7937, 0.1600, 0.0363],
        [0.6519, 0.8343, 0.7950, 0.2099],
        [0.7750, 0.7374, 0.5148, 0.7441]])
tensor([[-0.8937,  0.8014, -2.3330,  0.1942],
        [ 0.8274, -2.2576,  2.3836,  0.1034],
        [-0.9175,  0.2731, -1.2084,  0.4845]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


Bài 3. Kiểm tra thông tin Tensor

In [4]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


Bài 4. Slicing và Indexing

In [5]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-0.4750,  0.1941,  0.1565, -0.3822, -0.1779],
         [ 0.5950, -0.3902, -0.1751,  0.4548, -0.3955],
         [-0.6018,  1.2466, -0.9225,  0.0308, -0.9034],
         [-1.2793,  0.4508,  1.0533, -0.2193,  0.4260]],

        [[ 0.1452, -0.8703, -0.6854, -0.2983, -1.0786],
         [-1.5692,  0.2414,  1.2261, -1.4328,  0.4252],
         [-0.4873, -0.2809, -0.9331, -0.6912, -0.1471],
         [ 0.3002,  0.2675, -0.9534,  0.1143, -0.0751]],

        [[ 1.1916, -0.0993, -0.3743, -1.0397,  0.1017],
         [-1.4302, -0.4480,  0.7566,  0.7568, -0.1623],
         [-0.3415,  0.5319,  0.1654,  0.0247, -0.8298],
         [ 0.8706, -1.2591,  1.1789, -0.9453,  0.2741]]])

Tensor a[1]:
tensor([[ 0.1452, -0.8703, -0.6854, -0.2983, -1.0786],
        [-1.5692,  0.2414,  1.2261, -1.4328,  0.4252],
        [-0.4873, -0.2809, -0.9331, -0.6912, -0.1471],
        [ 0.3002,  0.2675, -0.9534,  0.1143, -0.0751]])

Tensor a[1:, 2:4]:
tensor([[[-0.4873, -0.2809, -0.9331, -0.6912, -0.1

Bài 5. Reshape và Flatten

In [6]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[ 0.4434,  1.0433, -0.0320, -0.8226],
        [ 1.0545,  1.2402,  1.3869, -0.7365],
        [ 0.4744,  0.0148, -0.5826,  0.1225]])

Flatten:
tensor([ 0.4434,  1.0433, -0.0320, -0.8226,  1.0545,  1.2402,  1.3869, -0.7365,
         0.4744,  0.0148, -0.5826,  0.1225])

Reshape to 3 x 2 x 2:
tensor([[[ 0.4434,  1.0433],
         [-0.0320, -0.8226]],

        [[ 1.0545,  1.2402],
         [ 1.3869, -0.7365]],

        [[ 0.4744,  0.0148],
         [-0.5826,  0.1225]]])


Bài 6. Phép toán và nhân ma trận

In [7]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 0.7217,  0.3150, -1.7614],
        [-1.6741, -0.1370, -0.1607]])
b:
tensor([[-0.0415, -1.1648, -1.1876],
        [-0.6742, -0.2709, -0.5670]])

a + b:
tensor([[ 0.6802, -0.8498, -2.9489],
        [-2.3483, -0.4079, -0.7277]])

a / b:
tensor([[-17.3936,  -0.2704,   1.4831],
        [  2.4829,   0.5055,   0.2834]])

a^2:
tensor([[0.5208, 0.0992, 3.1024],
        [2.8025, 0.0188, 0.0258]])

Matrix multiplication:
tensor([[1.6950, 0.4269],
        [0.4198, 1.2569]])


Bài 7. Các hàm thống kê trên Tensor

In [8]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[-0.2379,  0.0936,  0.4205, -0.4746],
        [-0.4595, -0.2474,  1.9435,  0.7392],
        [ 0.2534,  0.2990,  0.6839,  0.3017]])

Mean:
tensor([-0.1480,  0.0484,  1.0160,  0.1888])

Standard deviation:
tensor([0.3648, 0.2760, 0.8140, 0.6148])

Cumulative sum:
tensor([[-0.2379,  0.0936,  0.4205, -0.4746],
        [-0.6974, -0.1538,  2.3641,  0.2646],
        [-0.4440,  0.1452,  3.0480,  0.5663]])


Bài 8. Autograd cơ bản

In [9]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


Bài 9. Gradient Descent tìm hệ số đa thức

In [10]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
y_pred = x @ w
mse = torch.mean(torch.square(y - y_pred))
mse.backward()
optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[0.9058],
        [0.0155],
        [0.9031]], requires_grad=True)
Learned coefficients:
tensor([[0.9163],
        [0.0261],
        [0.9136]], requires_grad=True)


Bài 10. Giải hệ phương trình bằng Autograd

In [11]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
y2 = C - D - 1
y3 = A + C - 8
y4 = B - D - 2
sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
optimizer.zero_grad()
sqerr.backward()
optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(0.1378, requires_grad=True)
B = tensor(0.1464, requires_grad=True)
C = tensor(0.9065, requires_grad=True)
D = tensor(0.0202, requires_grad=True)


Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau

In [12]:
import torch

#Tạo Tensor X và reshape theo các kích thước yêu cầu
X = torch.arange(24)
X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)
print("X =", X)
print("X reshape (4, 6):\n", X_4x6)
print("X reshape (2, 12):\n", X_2x12)
print("X reshape (2, 3, 4):\n", X_2x3x4)

#Các phép toán trên hai Tensor kích thước 3 x 4
A = torch.arange(1, 13, dtype=torch.float32).reshape(3, 4)
B = torch.arange(2, 26, 2, dtype=torch.float32).reshape(3, 4)
print("\nA =\n", A)
print("B =\n", B)
print("A + B =\n", A + B)
print("A * B =\n", A * B)
print("A / B =\n", A / B)
print("Trung bình theo cột =", A.mean(dim=0))
print("Độ lệch chuẩn theo cột =", A.std(dim=0))

#Tính dy/dx bằng autograd và kiểm tra thủ công
x_autograd = torch.tensor(2.0, requires_grad=True)
y_autograd = 2 * x_autograd**2 + 5 * x_autograd + 3
dy_dx = torch.autograd.grad(y_autograd, x_autograd)[0]
dy_dx_manual = 4 * x_autograd + 5
print("\ny tại x = 2:", y_autograd.item())
print("dy/dx bằng autograd:", dy_dx.item())
print("dy/dx thủ công:", dy_dx_manual.item())
print("Hai kết quả bằng nhau:", torch.isclose(dy_dx, dy_dx_manual).item())

#Huấn luyện y = 2x^2 - 3x + 5 bằng Gradient Descent
x_train = torch.linspace(-5, 5, 100).reshape(-1, 1)
y_train = 2 * x_train**2 - 3 * x_train + 5
coefficients = torch.randn(3, 1, requires_grad=True)
optimizer = torch.optim.Adam([coefficients], lr=0.05)
x_features = torch.cat([x_train**2, x_train, torch.ones_like(x_train)], dim=1)

for _ in range(2000):
    y_pred = x_features @ coefficients
    loss = torch.mean((y_pred - y_train)**2)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

learned = coefficients.detach().flatten()
print("\nHệ số tìm được [a, b, c] trong y = ax^2 + bx + c:", learned)
print("Sai số cuối cùng:", loss.item())

X = tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
X reshape (4, 6):
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
X reshape (2, 12):
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
X reshape (2, 3, 4):
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

A =
 tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
B =
 tensor([[ 2.,  4.,  6.,  8.],
        [10., 12., 14., 16.],
        [18., 20., 22., 24.]])
A + B =
 tensor([[ 3.,  6.,  9., 12.],
        [15., 18., 21., 24.],
        [27., 30., 33., 36.]])
A * B =
 tensor([[  2.,   8.,  18.,  32.],
        [ 50.,  72.,  98., 128.],
        [162., 200., 242., 288.]